Numpy

Most powerful numerical processing.
Array oriented computing



In [1]:
a = [1,5,10,2]
print(a[2])

10


In [2]:
! pip install numpy

In [6]:
import numpy as np

In [3]:
l = list([1,2,3,4,5])
print(l)
print(type(l))

[1, 2, 3, 4, 5]
<class 'list'>


In [4]:
t = tuple([1,2,3,4,5])
print(t)
print(type(t))

(1, 2, 3, 4, 5)
<class 'tuple'>


In [7]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
arr = np.arange(10)
print(arr)
print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [11]:
%%time

lst = list(range(1000000))

for i in range(1000000):
    lst[i] *= lst[i]

CPU times: user 263 ms, sys: 20 ms, total: 283 ms
Wall time: 289 ms


In [12]:
%%time

arr = np.arange(1000000)

arr = arr * arr

CPU times: user 6.29 ms, sys: 9.13 ms, total: 15.4 ms
Wall time: 14.4 ms


In [18]:
lst = list(range(5))

for i in range(5):
    lst[i] *= lst[i]
    print('mul:', lst[i])
    lst[i] += lst[i]
    print('sum:',lst[i])

mul: 0
sum: 0
mul: 1
sum: 2
mul: 4
sum: 8
mul: 9
sum: 18
mul: 16
sum: 32


# Creating an Array

Array --> data is Homogenous
List. --> data can be Heterogenous

In [21]:
arr = np.array([1,2,3,4,5])
print(arr)

arr1 = np.array([1,2,3,4,'TFA'])
print(arr1)


[1 2 3 4 5]
['1' '2' '3' '4' 'TFA']


In [26]:
arr = np.array([1,2,3,4])

print(arr)
print(arr.ndim)
print(arr.shape)
print(len(arr))
print(arr.dtype)
print(arr.itemsize)

[1 2 3 4]
1
(4,)
4
int64
8


In [30]:
arr = np.array([1.5,2,3,4,5])

print(arr)
print(arr.ndim)
print(arr.shape)
print(len(arr))
print(arr.dtype)
print(arr.itemsize)

[1.5 2.  3.  4.  5. ]
1
(5,)
5
float64
8


In [31]:
arr = np.array([1.5,2,3,4, 5,'tfa'])

print(arr)
print(arr.ndim)
print(arr.shape)
print(len(arr))
print(arr.dtype)
print(arr.itemsize)

['1.5' '2' '3' '4' '5' 'tfa']
1
(6,)
6
<U32
128


In [45]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(len(arr))
print(arr.dtype)
print(arr.itemsize)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
2
int64
8


In [33]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(len(arr))
print(arr.dtype)
print(arr.itemsize)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
3
int64
8


In [39]:
arr = np.array([[1.5,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(len(arr))
print(arr.dtype)
print(arr.itemsize)
print(np.diag(arr))

[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]
 [ 7.   8.   9. ]
 [10.  11.  12. ]]
2
(4, 3)
4
float64
8
[1.5 5.  9. ]


In [48]:
arr = np.arange(24).reshape(2,3,4)
print(arr)
print(arr.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3


In [62]:
# 3D array - collection of multiple 2D array
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[7,8,9],[10,11,12]]])

print(arr)
print(arr.ndim)
print(arr.shape)
print(len(arr))
print(arr.dtype)
print(arr.itemsize)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 7  8  9]
  [10 11 12]]]
3
(3, 2, 3)
3
int64
8


In [63]:
# 3D array - collection of multiple 2D array
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[7,8,9],[10,11,12]]])

print(arr)
print(arr.ndim)
print(arr.shape)
print(len(arr))
print(arr.dtype)
print(arr.itemsize)
print(np.diag(arr))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 7  8  9]
  [10 11 12]]]
3
(3, 2, 3)
3
int64
8


ValueError: Input must be 1- or 2-d.

# Functions for creating an array

In [60]:
arr = np.ones((3,3))
print(arr)
print(arr.ndim)
print(arr.shape)
print(len(arr))
print(arr.dtype)
print(arr.itemsize)
print(np.diag(arr))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2
(3, 3)
3
float64
8
[1. 1. 1.]


In [64]:
arr = np.zeros((7,3))
print(arr)
print(arr.ndim)
print(arr.shape)
print(len(arr))
print(arr.dtype)
print(arr.itemsize)
print(np.diag(arr))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2
(7, 3)
7
float64
8
[0. 0. 0.]


# identity matix
--> it should be a square matrix (# rows = # colums)
--> it's diagonals are 1s and others are 0s

In [75]:
arr = np.eye(2,2)
print(arr)

#arr1 = np.eye(3)
arr1 = np.eye(3,3)
print(arr1)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [74]:
arr1 = np.eye(3,4)
print(arr1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [86]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[0])
print(arr[0,1])
arr[0,1] = 2.5
print(arr)

[[1 2 3]
 [4 5 6]]
[1 2 3]
2
[[1 2 3]
 [4 5 6]]


In [90]:
arr = np.arange(10)
print(arr)
print(len(arr))

[0 1 2 3 4 5 6 7 8 9]
10


In [91]:
arr = np.arange(1,10)
print(arr)
print(len(arr))

[1 2 3 4 5 6 7 8 9]
9


In [92]:
arr = np.arange(1,10,2)
print(arr)
print(len(arr))

[1 3 5 7 9]
5


In [96]:
arr = np.random.random(2,2)
print(arr)

TypeError: random() takes at most 1 positional argument (2 given)

In [97]:
arr = np.random.random((2,2))
print(arr)

[[0.52773079 0.35281825]
 [0.25047729 0.52937571]]


In [100]:
arr = np.random.random([2,2])
print(arr)
print(arr.dtype)

[[0.17116403 0.29850371]
 [0.4304768  0.28590537]]
float64


In [106]:
arr = np.random.randint((1,10,4))
print(arr)

[0 5 2]
