In [1]:
import numpy as np

In [2]:
arr = 3 * np.arange(10)
print(arr)
print(arr[2])

[ 0  3  6  9 12 15 18 21 24 27]
6


In [3]:
print(arr[10])

IndexError: index 10 is out of bounds for axis 0 with size 10

In [5]:
l = [1, 2, 3]
t = (1, 2, 3)

l[2] = 99
print(l)

t[2] = 99
print(t)

[1, 2, 99]


TypeError: 'tuple' object does not support item assignment

In [14]:
l = list([[1,2,3],[4,5,6]])
print(l[1][2])

6


In [13]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr)

print(arr[1])
print(arr[1,2])
print(arr[0,1])


[[1 2 3]
 [4 5 6]]
[4 5 6]
6
2


In [16]:
arr[1,2] = 99
print(arr)

[[ 1  2  3]
 [ 4  5 99]]


In [32]:
arr = np.array([[1,2],[3,4],[5,6]])
print(arr)
print(arr[2,1])
print(arr[[0,1,2],[0,1,0]])
print('--')
print(arr[[0,0,2],[0]])
print('--')
print(arr[[0,0,2],[0,1,1]])

[[1 2]
 [3 4]
 [5 6]]
6
[1 4 5]
--
[1 1 5]
--
[1 2 6]


In [52]:
arr = np.arange(10)

print(arr)
print(arr[::2])
print(arr[::-1])
print(arr[1:5])
print('---')
print(arr[5:1])
print('---')
print(arr[5::1])
print('---')
print(arr[5:-1])
print(arr[5::-1])

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]
[1 2 3 4]
---
[]
---
[5 6 7 8 9]
---
[5 6 7 8]
[5 4 3 2 1 0]


In [56]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr[:2, 1:3])
print(arr[1:2, : ])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
[[5 6 7 8]]


In [5]:
import numpy as np
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x)
print(y)
print('*'*40)
print(np.add(x,y))
print('*'*40)
print(np.subtract(y,x))
print('*'*40)
print(np.multiply(x,y))
print('*'*40)
print(np.divide(x,y))
print('*'*40)
print(np.multiply(x,-1))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
****************************************
[[ 6  8]
 [10 12]]
****************************************
[[4 4]
 [4 4]]
****************************************
[[ 5 12]
 [21 32]]
****************************************
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
****************************************
[[-1 -2]
 [-3 -4]]


In [16]:
x = np.array([1,2])
y = np.array([[1,2],[3,4]])

print(np.multiply(x,y))
print('*'*40)
print(np.matmul(x,y))

[[1 4]
 [3 8]]
****************************************
[ 7 10]


In [3]:
import numpy as np
x = np.array([[1,2],[3,4]])
y = np.array([[1,2],[4,5]])

print(x)
print(y)

print(np.multiply(x,y))
print('*'*40)
print(np.matmul(x,y))
print('*'*40)
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[1 2]
 [4 5]]
[[ 1  4]
 [12 20]]
****************************************
[[ 9 12]
 [19 26]]
****************************************
[[ 9 12]
 [19 26]]


In [13]:
x = np.array([1,2])
y = np.array([[1,2],[3,4],[5,6]])

print(np.multiply(x,y))
print(np.matmul(x,y))

[[ 1  4]
 [ 3  8]
 [ 5 12]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [18]:
x = np.array([1,2])
y = np.array([[1,2],[3,4],[5,6]])

print(np.multiply(x,y))
print(np.dot(x,y))

[[ 1  4]
 [ 3  8]
 [ 5 12]]


ValueError: shapes (2,) and (3,2) not aligned: 2 (dim 0) != 3 (dim 0)

In [21]:
x = np.array([[1,2],[3,4]])
print(x)
print(np.sum(x))
print(np.sum(x,axis=0)) # column wise
print(np.sum(x,axis=1)) # row wise

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [22]:
print(np.min(x))
print(np.max(x))

1
4


In [23]:
print(x)
print('*'*40)
print(x.T)

[[1 2]
 [3 4]]
****************************************
[[1 3]
 [2 4]]


In [24]:
np.exp(1)

2.718281828459045

In [25]:
np.exp(2)

7.38905609893065

# Numpy Statistics 

In [26]:
x = np.array([160,182,184,124,125])

In [27]:
print(np.max(x))
print(np.min(x))

184
124


In [28]:
print(np.mean(x))
print(np.median(x))
print(np.var(x))
print(np.std(x))

155.0
160.0
691.2
26.290682760247975


In [30]:
heights = np.array([160,182,184,124,125,134])
weights = np.array([50,78,45,51,80,60])

np.corrcoef(heights,weights)

array([[ 1.        , -0.14738888],
       [-0.14738888,  1.        ]])

# Numpy Broadcasting

In [31]:
import numpy as np

In [4]:
arr_1 = np.array([[1,2,3],[4,5,6]])
print(arr_1)
arr_2 = np.array([1,2,3])
print(arr_2)
print(arr_1 + arr_2)

[[1 2 3]
 [4 5 6]]
[1 2 3]
[[2 4 6]
 [5 7 9]]


In [5]:
arr_1 = np.array([[1,2,3],[4,5,6]])
print(arr_1)
arr_2 = np.array([[1],[2]])
print(arr_2)
print(arr_1 + arr_2)

[[1 2 3]
 [4 5 6]]
[[1]
 [2]]
[[2 3 4]
 [6 7 8]]


In [35]:
arr_1 = np.array([[1,2,3],[4,5,6]])
arr_2 = np.array([1])
print(arr_1 + arr_2)

[[2 3 4]
 [5 6 7]]


In [7]:
arr_1 = np.array([1,2,3,4,5])
print(arr_1)
arr_2 = np.array([1,2,3,4])
print(arr_2)
print(arr_1 + arr_2)

[1 2 3 4 5]
[1 2 3 4]


ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [15]:
arr_1 = np.array([[1],[2],[3],[4],[5]])
print(arr_1)
print(arr_1.shape)
arr_2 = np.array([1,2,3,4])
print(arr_2)
print(arr_2.shape)
print(arr_1 + arr_2)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)
[1 2 3 4]
(4,)
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]
